# Copyright (C) 2018 Swift Navigation Inc.
# Contact: Swift Navigation <dev@swiftnav.com>
#
# LSN Travis Build File.

# **********************************************************************
# PROJECT SETUP
# **********************************************************************

# Travis does not yet fully support bionic, so we need to keep it at Xenial until fixed.
dist:  xenial
sudo:  false
group: stable

language: c

cache:
  apt: true
  directories:

# **********************************************************************
# BUILD MATRIX:
# **********************************************************************
matrix:
  # Non-critical matrix entries will not block build completion.
  fast_finish: true

  # Enumerate all builds and their dependencies.
  include:
    # ------------------------------------------------------------------
    # Unit and integration test builds with GCC.
    # ------------------------------------------------------------------

    # GCC 6 / Unit Test.
    - env: TEST_SUITE=unit
      compiler: gcc-6
      addons: { apt: { packages: ["cmake",
                                  "gcc-6",
                                  "g++-6",
                                  "check"],
                       sources: ["ubuntu-toolchain-r-test"] } }

    # ------------------------------------------------------------------
    # Lint and check compilation builds with Clang
    # ------------------------------------------------------------------
    # CLANG / Lint
    - env: TEST_SUITE=lint
      compiler: clang-6.0
      addons: { apt: { packages: ["cmake",
                                  "clang-6.0",
                                  "clang-format-6.0",
                                  "clang-tidy-6.0",
                                  "libc++-dev",
                                  "libc++abi-dev"] } }


# **********************************************************************
# INSTALL AND BUILD STEPS:
# **********************************************************************

# Build is handled by a shell script.
script:
  - bash ./travis.sh
